services:
  arepas_db:
    image: postgres:17.2
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: arepas
      POSTGRES_PASSWORD: arepas2025
      POSTGRES_DB: arepas_db
volumes:
  data:
    external: false
